const ServiceData =

    [
        {
            id: 1,
            title: "Nature Beauty",
            description: "Explore the breathtaking beauty of nature with this stunning image.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 2,
            title: "City Lights",
            description: "A mesmerizing view of city lights during the night.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/5439391/pexels-photo-5439391.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 3,
            title: "Adventure Awaits",
            description: "Embark on a journey filled with excitement and discovery.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/7518943/pexels-photo-7518943.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        // Add more entries as needed...
        {
            id: 4,
            title: "Sunset Serenity",
            description: "Witness the tranquil beauty of a sunset over the horizon.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/4047781/pexels-photo-4047781.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
         {
            id: 5,
            title: "Great workday",
            description: "Explore the breathtaking beauty of nature with this stunning image.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/3182833/pexels-photo-3182833.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 6,
            title: "Meeting in my mind",
            description: "A mesmerizing view of city lights during the night.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/4078343/pexels-photo-4078343.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 7,
            title: "Adventure Awaits",
            description: "Embark on a journey filled with excitement and discovery.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/1181371/pexels-photo-1181371.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 8,
            title: "Sunset Serenity",
            description: "Witness the tranquil beauty of a sunset over the horizon.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/3893054/pexels-photo-3893054.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
         {
            id: 9,
            title: "Great workday",
            description: "Explore the breathtaking beauty of nature with this stunning image.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/5257189/pexels-photo-5257189.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 10,
            title: "Meeting in my mind",
            description: "A mesmerizing view of city lights during the night.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/6773397/pexels-photo-6773397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1"
        },
        {
            id: 11,
            title: "Adventure Awaits",
            description: "Embark on a journey filled with excitement and discovery.",
            description_all: "Certainly! Without specific details about the place you have in mind, I'll provide a general description of a breathtaking natural setting:Imagine standing on the edge of a vast and pristine landscape, where the air is crisp and filled with the invigorating scent of pine trees. Before you stretches a panoramic view of majestic mountains, their snow-capped peaks glistening in the sunlight. The mountains cradle a serene valley below, adorned with a tapestry of lush, vibrant greenery.A crystal-clear river meanders through the valley, reflecting the azure sky above. The soothing sound of the water flowing over smooth stones creates a melody that harmonizes with the gentle rustling of leaves in the surrounding forest. Towering trees, their branches forming a cathedral-like canopy, provide shade and a sense of sanctuary.Wildflowers of every color imaginable carpet the meadows, painting the landscape with a palette of nature's finest hues. Butterflies dance in the warm breeze, adding a touch of delicate grace to the scene. In the distance, a waterfall cascades from a cliff, its ethereal mist catching the sunlight, creating rainbows that dance in the air.As you take in the breathtaking beauty of this stunning place, a profound sense of peace and connection to the natural world envelops you. It's a sanctuary where time seems to stand still, inviting contemplation and appreciation for the wonders of our planet.",
            image_url: "https://images.pexels.com/photos/3153198/pexels-photo-3153198.jpeg?auto=compress&cs=tinysrgb&w=600"
        }
    ]
    


export default ServiceData;